# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 6586cb00f6fe61baabf2a386d8243e13da9c7cab8f87235415726f1078e1933602792048c6d2285070193161026ed971678e06b335c87f7fb0cbb254b44c219f

test:
  secret_key_base: 2e15afc4dbe5de167400ad284414c95c4e43ef799ae6f477e453d2cbfcc5d8976c740f844e22588ec98898d59b121a9b63818a591eb8dbb6e21641419028ae6b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
